/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.resources.querytypes.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.api.core.Nullable;
import io.github.payabli.api.core.NullableNonemptyFilter;
import io.github.payabli.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TransferOutSummary.Builder.class)
public final class TransferOutSummary {
    private final Optional<Integer> totalPages;

    private final Optional<Integer> totalRecords;

    private final Optional<Integer> pageSize;

    private final Map<String, Object> additionalProperties;

    private TransferOutSummary(
            Optional<Integer> totalPages,
            Optional<Integer> totalRecords,
            Optional<Integer> pageSize,
            Map<String, Object> additionalProperties) {
        this.totalPages = totalPages;
        this.totalRecords = totalRecords;
        this.pageSize = pageSize;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Number of pages in the response.
     */
    @JsonIgnore
    public Optional<Integer> getTotalPages() {
        if (totalPages == null) {
            return Optional.empty();
        }
        return totalPages;
    }

    /**
     * @return Number of records in the response.
     */
    @JsonIgnore
    public Optional<Integer> getTotalRecords() {
        if (totalRecords == null) {
            return Optional.empty();
        }
        return totalRecords;
    }

    /**
     * @return Number of records per page.
     */
    @JsonIgnore
    public Optional<Integer> getPageSize() {
        if (pageSize == null) {
            return Optional.empty();
        }
        return pageSize;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("totalPages")
    private Optional<Integer> _getTotalPages() {
        return totalPages;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("totalRecords")
    private Optional<Integer> _getTotalRecords() {
        return totalRecords;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("pageSize")
    private Optional<Integer> _getPageSize() {
        return pageSize;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TransferOutSummary && equalTo((TransferOutSummary) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TransferOutSummary other) {
        return totalPages.equals(other.totalPages)
                && totalRecords.equals(other.totalRecords)
                && pageSize.equals(other.pageSize);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.totalPages, this.totalRecords, this.pageSize);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> totalPages = Optional.empty();

        private Optional<Integer> totalRecords = Optional.empty();

        private Optional<Integer> pageSize = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TransferOutSummary other) {
            totalPages(other.getTotalPages());
            totalRecords(other.getTotalRecords());
            pageSize(other.getPageSize());
            return this;
        }

        /**
         * <p>Number of pages in the response.</p>
         */
        @JsonSetter(value = "totalPages", nulls = Nulls.SKIP)
        public Builder totalPages(Optional<Integer> totalPages) {
            this.totalPages = totalPages;
            return this;
        }

        public Builder totalPages(Integer totalPages) {
            this.totalPages = Optional.ofNullable(totalPages);
            return this;
        }

        public Builder totalPages(Nullable<Integer> totalPages) {
            if (totalPages.isNull()) {
                this.totalPages = null;
            } else if (totalPages.isEmpty()) {
                this.totalPages = Optional.empty();
            } else {
                this.totalPages = Optional.of(totalPages.get());
            }
            return this;
        }

        /**
         * <p>Number of records in the response.</p>
         */
        @JsonSetter(value = "totalRecords", nulls = Nulls.SKIP)
        public Builder totalRecords(Optional<Integer> totalRecords) {
            this.totalRecords = totalRecords;
            return this;
        }

        public Builder totalRecords(Integer totalRecords) {
            this.totalRecords = Optional.ofNullable(totalRecords);
            return this;
        }

        public Builder totalRecords(Nullable<Integer> totalRecords) {
            if (totalRecords.isNull()) {
                this.totalRecords = null;
            } else if (totalRecords.isEmpty()) {
                this.totalRecords = Optional.empty();
            } else {
                this.totalRecords = Optional.of(totalRecords.get());
            }
            return this;
        }

        /**
         * <p>Number of records per page.</p>
         */
        @JsonSetter(value = "pageSize", nulls = Nulls.SKIP)
        public Builder pageSize(Optional<Integer> pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        public Builder pageSize(Integer pageSize) {
            this.pageSize = Optional.ofNullable(pageSize);
            return this;
        }

        public Builder pageSize(Nullable<Integer> pageSize) {
            if (pageSize.isNull()) {
                this.pageSize = null;
            } else if (pageSize.isEmpty()) {
                this.pageSize = Optional.empty();
            } else {
                this.pageSize = Optional.of(pageSize.get());
            }
            return this;
        }

        public TransferOutSummary build() {
            return new TransferOutSummary(totalPages, totalRecords, pageSize, additionalProperties);
        }
    }
}
