/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.resources.taptopay.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TapToPayActivationChallengeRequest.Builder.class)
public final class TapToPayActivationChallengeRequest {
    private final String entry;

    private final String deviceId;

    private final Map<String, Object> additionalProperties;

    private TapToPayActivationChallengeRequest(
            String entry, String deviceId, Map<String, Object> additionalProperties) {
        this.entry = entry;
        this.deviceId = deviceId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("entry")
    public String getEntry() {
        return entry;
    }

    /**
     * @return The device identifier (<code>poiId</code>) returned when the device was registered.
     */
    @JsonProperty("deviceId")
    public String getDeviceId() {
        return deviceId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TapToPayActivationChallengeRequest
                && equalTo((TapToPayActivationChallengeRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TapToPayActivationChallengeRequest other) {
        return entry.equals(other.entry) && deviceId.equals(other.deviceId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.entry, this.deviceId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EntryStage builder() {
        return new Builder();
    }

    public interface EntryStage {
        DeviceIdStage entry(@NotNull String entry);

        Builder from(TapToPayActivationChallengeRequest other);
    }

    public interface DeviceIdStage {
        /**
         * <p>The device identifier (<code>poiId</code>) returned when the device was registered.</p>
         */
        _FinalStage deviceId(@NotNull String deviceId);
    }

    public interface _FinalStage {
        TapToPayActivationChallengeRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EntryStage, DeviceIdStage, _FinalStage {
        private String entry;

        private String deviceId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TapToPayActivationChallengeRequest other) {
            entry(other.getEntry());
            deviceId(other.getDeviceId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("entry")
        public DeviceIdStage entry(@NotNull String entry) {
            this.entry = Objects.requireNonNull(entry, "entry must not be null");
            return this;
        }

        /**
         * <p>The device identifier (<code>poiId</code>) returned when the device was registered.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("deviceId")
        public _FinalStage deviceId(@NotNull String deviceId) {
            this.deviceId = Objects.requireNonNull(deviceId, "deviceId must not be null");
            return this;
        }

        @java.lang.Override
        public TapToPayActivationChallengeRequest build() {
            return new TapToPayActivationChallengeRequest(entry, deviceId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
