/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payabli.api.resources.vendorv;

import com.payabli.api.core.ClientOptions;
import com.payabli.api.core.RequestOptions;
import com.payabli.api.types.PayabliApiResponseVendors;
import com.payabli.api.types.VendorData;
import com.payabli.api.types.VendorQueryRecord;
import java.util.concurrent.CompletableFuture;

public class AsyncVendorvClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawVendorvClient rawClient;

    public AsyncVendorvClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawVendorvClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawVendorvClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Creates a vendor in an entrypoint.
     */
    public CompletableFuture<PayabliApiResponseVendors> addVendor(String entry) {
        return this.rawClient.addVendor(entry).thenApply(response -> response.body());
    }

    /**
     * Creates a vendor in an entrypoint.
     */
    public CompletableFuture<PayabliApiResponseVendors> addVendor(String entry, VendorData request) {
        return this.rawClient.addVendor(entry, request).thenApply(response -> response.body());
    }

    /**
     * Creates a vendor in an entrypoint.
     */
    public CompletableFuture<PayabliApiResponseVendors> addVendor(
            String entry, VendorData request, RequestOptions requestOptions) {
        return this.rawClient.addVendor(entry, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Delete a vendor.
     */
    public CompletableFuture<PayabliApiResponseVendors> deleteVendor(int idVendor) {
        return this.rawClient.deleteVendor(idVendor).thenApply(response -> response.body());
    }

    /**
     * Delete a vendor.
     */
    public CompletableFuture<PayabliApiResponseVendors> deleteVendor(int idVendor, RequestOptions requestOptions) {
        return this.rawClient.deleteVendor(idVendor, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Updates a vendor's information. Send only the fields you need to update.
     */
    public CompletableFuture<PayabliApiResponseVendors> editVendor(int idVendor) {
        return this.rawClient.editVendor(idVendor).thenApply(response -> response.body());
    }

    /**
     * Updates a vendor's information. Send only the fields you need to update.
     */
    public CompletableFuture<PayabliApiResponseVendors> editVendor(int idVendor, VendorData request) {
        return this.rawClient.editVendor(idVendor, request).thenApply(response -> response.body());
    }

    /**
     * Updates a vendor's information. Send only the fields you need to update.
     */
    public CompletableFuture<PayabliApiResponseVendors> editVendor(
            int idVendor, VendorData request, RequestOptions requestOptions) {
        return this.rawClient.editVendor(idVendor, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves a vendor's details.
     */
    public CompletableFuture<VendorQueryRecord> getVendor(int idVendor) {
        return this.rawClient.getVendor(idVendor).thenApply(response -> response.body());
    }

    /**
     * Retrieves a vendor's details.
     */
    public CompletableFuture<VendorQueryRecord> getVendor(int idVendor, RequestOptions requestOptions) {
        return this.rawClient.getVendor(idVendor, requestOptions).thenApply(response -> response.body());
    }
}
