/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payabli.api.resources.invoice.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payabli.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SendInvoiceRequest.Builder.class)
public final class SendInvoiceRequest {
    private final Optional<Boolean> attachfile;

    private final Optional<String> mail2;

    private final Map<String, Object> additionalProperties;

    private SendInvoiceRequest(
            Optional<Boolean> attachfile, Optional<String> mail2, Map<String, Object> additionalProperties) {
        this.attachfile = attachfile;
        this.mail2 = mail2;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return When <code>true</code>, attaches a PDF version of invoice to the email.
     */
    @JsonProperty("attachfile")
    public Optional<Boolean> getAttachfile() {
        return attachfile;
    }

    /**
     * @return Email address where the invoice will be sent to. If this parameter isn't included, Payabli uses the email address on file for the customer owner of the invoice.
     */
    @JsonProperty("mail2")
    public Optional<String> getMail2() {
        return mail2;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SendInvoiceRequest && equalTo((SendInvoiceRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SendInvoiceRequest other) {
        return attachfile.equals(other.attachfile) && mail2.equals(other.mail2);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.attachfile, this.mail2);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> attachfile = Optional.empty();

        private Optional<String> mail2 = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SendInvoiceRequest other) {
            attachfile(other.getAttachfile());
            mail2(other.getMail2());
            return this;
        }

        /**
         * <p>When <code>true</code>, attaches a PDF version of invoice to the email.</p>
         */
        @JsonSetter(value = "attachfile", nulls = Nulls.SKIP)
        public Builder attachfile(Optional<Boolean> attachfile) {
            this.attachfile = attachfile;
            return this;
        }

        public Builder attachfile(Boolean attachfile) {
            this.attachfile = Optional.ofNullable(attachfile);
            return this;
        }

        /**
         * <p>Email address where the invoice will be sent to. If this parameter isn't included, Payabli uses the email address on file for the customer owner of the invoice.</p>
         */
        @JsonSetter(value = "mail2", nulls = Nulls.SKIP)
        public Builder mail2(Optional<String> mail2) {
            this.mail2 = mail2;
            return this;
        }

        public Builder mail2(String mail2) {
            this.mail2 = Optional.ofNullable(mail2);
            return this;
        }

        public SendInvoiceRequest build() {
            return new SendInvoiceRequest(attachfile, mail2, additionalProperties);
        }
    }
}
