/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.resources.payoutsubscription.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.api.core.ObjectMappers;
import io.github.payabli.api.resources.moneyouttypes.types.AuthorizePaymentMethod;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdatePayoutSubscriptionBody.Builder.class)
public final class UpdatePayoutSubscriptionBody {
    private final Optional<Boolean> setPause;

    private final Optional<PayoutPaymentDetail> paymentDetails;

    private final Optional<AuthorizePaymentMethod> paymentMethod;

    private final Optional<PayoutScheduleDetail> scheduleDetails;

    private final Map<String, Object> additionalProperties;

    private UpdatePayoutSubscriptionBody(
            Optional<Boolean> setPause,
            Optional<PayoutPaymentDetail> paymentDetails,
            Optional<AuthorizePaymentMethod> paymentMethod,
            Optional<PayoutScheduleDetail> scheduleDetails,
            Map<String, Object> additionalProperties) {
        this.setPause = setPause;
        this.paymentDetails = paymentDetails;
        this.paymentMethod = paymentMethod;
        this.scheduleDetails = scheduleDetails;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("setPause")
    public Optional<Boolean> getSetPause() {
        return setPause;
    }

    /**
     * @return Object describing details of the payout.
     */
    @JsonProperty("paymentDetails")
    public Optional<PayoutPaymentDetail> getPaymentDetails() {
        return paymentDetails;
    }

    @JsonProperty("paymentMethod")
    public Optional<AuthorizePaymentMethod> getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * @return Object describing the schedule for the payout subscription.
     */
    @JsonProperty("scheduleDetails")
    public Optional<PayoutScheduleDetail> getScheduleDetails() {
        return scheduleDetails;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdatePayoutSubscriptionBody && equalTo((UpdatePayoutSubscriptionBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdatePayoutSubscriptionBody other) {
        return setPause.equals(other.setPause)
                && paymentDetails.equals(other.paymentDetails)
                && paymentMethod.equals(other.paymentMethod)
                && scheduleDetails.equals(other.scheduleDetails);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.setPause, this.paymentDetails, this.paymentMethod, this.scheduleDetails);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> setPause = Optional.empty();

        private Optional<PayoutPaymentDetail> paymentDetails = Optional.empty();

        private Optional<AuthorizePaymentMethod> paymentMethod = Optional.empty();

        private Optional<PayoutScheduleDetail> scheduleDetails = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdatePayoutSubscriptionBody other) {
            setPause(other.getSetPause());
            paymentDetails(other.getPaymentDetails());
            paymentMethod(other.getPaymentMethod());
            scheduleDetails(other.getScheduleDetails());
            return this;
        }

        @JsonSetter(value = "setPause", nulls = Nulls.SKIP)
        public Builder setPause(Optional<Boolean> setPause) {
            this.setPause = setPause;
            return this;
        }

        public Builder setPause(Boolean setPause) {
            this.setPause = Optional.ofNullable(setPause);
            return this;
        }

        /**
         * <p>Object describing details of the payout.</p>
         */
        @JsonSetter(value = "paymentDetails", nulls = Nulls.SKIP)
        public Builder paymentDetails(Optional<PayoutPaymentDetail> paymentDetails) {
            this.paymentDetails = paymentDetails;
            return this;
        }

        public Builder paymentDetails(PayoutPaymentDetail paymentDetails) {
            this.paymentDetails = Optional.ofNullable(paymentDetails);
            return this;
        }

        @JsonSetter(value = "paymentMethod", nulls = Nulls.SKIP)
        public Builder paymentMethod(Optional<AuthorizePaymentMethod> paymentMethod) {
            this.paymentMethod = paymentMethod;
            return this;
        }

        public Builder paymentMethod(AuthorizePaymentMethod paymentMethod) {
            this.paymentMethod = Optional.ofNullable(paymentMethod);
            return this;
        }

        /**
         * <p>Object describing the schedule for the payout subscription.</p>
         */
        @JsonSetter(value = "scheduleDetails", nulls = Nulls.SKIP)
        public Builder scheduleDetails(Optional<PayoutScheduleDetail> scheduleDetails) {
            this.scheduleDetails = scheduleDetails;
            return this;
        }

        public Builder scheduleDetails(PayoutScheduleDetail scheduleDetails) {
            this.scheduleDetails = Optional.ofNullable(scheduleDetails);
            return this;
        }

        public UpdatePayoutSubscriptionBody build() {
            return new UpdatePayoutSubscriptionBody(
                    setPause, paymentDetails, paymentMethod, scheduleDetails, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
