/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.resources.notificationlogs.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.api.core.ObjectMappers;
import io.github.payabli.api.resources.notificationlogs.types.NotificationLogSearchRequest;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SearchNotificationLogsRequest.Builder.class)
public final class SearchNotificationLogsRequest {
    private final Optional<Integer> pageSize;

    private final Optional<Integer> skip;

    private final NotificationLogSearchRequest body;

    private final Map<String, Object> additionalProperties;

    private SearchNotificationLogsRequest(
            Optional<Integer> pageSize,
            Optional<Integer> skip,
            NotificationLogSearchRequest body,
            Map<String, Object> additionalProperties) {
        this.pageSize = pageSize;
        this.skip = skip;
        this.body = body;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("PageSize")
    public Optional<Integer> getPageSize() {
        return pageSize;
    }

    /**
     * @return The number of records to skip before starting to collect the result set.
     */
    @JsonProperty("Skip")
    public Optional<Integer> getSkip() {
        return skip;
    }

    @JsonProperty("body")
    public NotificationLogSearchRequest getBody() {
        return body;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SearchNotificationLogsRequest && equalTo((SearchNotificationLogsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SearchNotificationLogsRequest other) {
        return pageSize.equals(other.pageSize) && skip.equals(other.skip) && body.equals(other.body);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.pageSize, this.skip, this.body);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static BodyStage builder() {
        return new Builder();
    }

    public interface BodyStage {
        _FinalStage body(@NotNull NotificationLogSearchRequest body);

        Builder from(SearchNotificationLogsRequest other);
    }

    public interface _FinalStage {
        SearchNotificationLogsRequest build();

        _FinalStage pageSize(Optional<Integer> pageSize);

        _FinalStage pageSize(Integer pageSize);

        /**
         * <p>The number of records to skip before starting to collect the result set.</p>
         */
        _FinalStage skip(Optional<Integer> skip);

        _FinalStage skip(Integer skip);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements BodyStage, _FinalStage {
        private NotificationLogSearchRequest body;

        private Optional<Integer> skip = Optional.empty();

        private Optional<Integer> pageSize = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SearchNotificationLogsRequest other) {
            pageSize(other.getPageSize());
            skip(other.getSkip());
            body(other.getBody());
            return this;
        }

        @java.lang.Override
        @JsonSetter("body")
        public _FinalStage body(@NotNull NotificationLogSearchRequest body) {
            this.body = Objects.requireNonNull(body, "body must not be null");
            return this;
        }

        /**
         * <p>The number of records to skip before starting to collect the result set.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage skip(Integer skip) {
            this.skip = Optional.ofNullable(skip);
            return this;
        }

        /**
         * <p>The number of records to skip before starting to collect the result set.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "Skip", nulls = Nulls.SKIP)
        public _FinalStage skip(Optional<Integer> skip) {
            this.skip = skip;
            return this;
        }

        @java.lang.Override
        public _FinalStage pageSize(Integer pageSize) {
            this.pageSize = Optional.ofNullable(pageSize);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "PageSize", nulls = Nulls.SKIP)
        public _FinalStage pageSize(Optional<Integer> pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        @java.lang.Override
        public SearchNotificationLogsRequest build() {
            return new SearchNotificationLogsRequest(pageSize, skip, body, additionalProperties);
        }
    }
}
