/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.resources.bill.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.api.core.ObjectMappers;
import io.github.payabli.api.types.Responsedatanonobject;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BillResponse.Builder.class)
public final class BillResponse {
    private final Optional<Integer> responseCode;

    private final Optional<String> pageIdentifier;

    private final Optional<Long> roomId;

    private final Optional<Boolean> isSuccess;

    private final String responseText;

    private final Optional<Responsedatanonobject> responseData;

    private final Map<String, Object> additionalProperties;

    private BillResponse(
            Optional<Integer> responseCode,
            Optional<String> pageIdentifier,
            Optional<Long> roomId,
            Optional<Boolean> isSuccess,
            String responseText,
            Optional<Responsedatanonobject> responseData,
            Map<String, Object> additionalProperties) {
        this.responseCode = responseCode;
        this.pageIdentifier = pageIdentifier;
        this.roomId = roomId;
        this.isSuccess = isSuccess;
        this.responseText = responseText;
        this.responseData = responseData;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("responseCode")
    public Optional<Integer> getResponseCode() {
        return responseCode;
    }

    @JsonProperty("pageIdentifier")
    public Optional<String> getPageIdentifier() {
        return pageIdentifier;
    }

    @JsonProperty("roomId")
    public Optional<Long> getRoomId() {
        return roomId;
    }

    @JsonProperty("isSuccess")
    public Optional<Boolean> getIsSuccess() {
        return isSuccess;
    }

    @JsonProperty("responseText")
    public String getResponseText() {
        return responseText;
    }

    /**
     * @return If <code>isSuccess</code> = true, this contains the bill identifier. If <code>isSuccess</code> = false, this contains the reason for the error.
     */
    @JsonProperty("responseData")
    public Optional<Responsedatanonobject> getResponseData() {
        return responseData;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BillResponse && equalTo((BillResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BillResponse other) {
        return responseCode.equals(other.responseCode)
                && pageIdentifier.equals(other.pageIdentifier)
                && roomId.equals(other.roomId)
                && isSuccess.equals(other.isSuccess)
                && responseText.equals(other.responseText)
                && responseData.equals(other.responseData);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.responseCode,
                this.pageIdentifier,
                this.roomId,
                this.isSuccess,
                this.responseText,
                this.responseData);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ResponseTextStage builder() {
        return new Builder();
    }

    public interface ResponseTextStage {
        _FinalStage responseText(@NotNull String responseText);

        Builder from(BillResponse other);
    }

    public interface _FinalStage {
        BillResponse build();

        _FinalStage responseCode(Optional<Integer> responseCode);

        _FinalStage responseCode(Integer responseCode);

        _FinalStage pageIdentifier(Optional<String> pageIdentifier);

        _FinalStage pageIdentifier(String pageIdentifier);

        _FinalStage roomId(Optional<Long> roomId);

        _FinalStage roomId(Long roomId);

        _FinalStage isSuccess(Optional<Boolean> isSuccess);

        _FinalStage isSuccess(Boolean isSuccess);

        /**
         * <p>If <code>isSuccess</code> = true, this contains the bill identifier. If <code>isSuccess</code> = false, this contains the reason for the error.</p>
         */
        _FinalStage responseData(Optional<Responsedatanonobject> responseData);

        _FinalStage responseData(Responsedatanonobject responseData);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ResponseTextStage, _FinalStage {
        private String responseText;

        private Optional<Responsedatanonobject> responseData = Optional.empty();

        private Optional<Boolean> isSuccess = Optional.empty();

        private Optional<Long> roomId = Optional.empty();

        private Optional<String> pageIdentifier = Optional.empty();

        private Optional<Integer> responseCode = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(BillResponse other) {
            responseCode(other.getResponseCode());
            pageIdentifier(other.getPageIdentifier());
            roomId(other.getRoomId());
            isSuccess(other.getIsSuccess());
            responseText(other.getResponseText());
            responseData(other.getResponseData());
            return this;
        }

        @java.lang.Override
        @JsonSetter("responseText")
        public _FinalStage responseText(@NotNull String responseText) {
            this.responseText = Objects.requireNonNull(responseText, "responseText must not be null");
            return this;
        }

        /**
         * <p>If <code>isSuccess</code> = true, this contains the bill identifier. If <code>isSuccess</code> = false, this contains the reason for the error.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage responseData(Responsedatanonobject responseData) {
            this.responseData = Optional.ofNullable(responseData);
            return this;
        }

        /**
         * <p>If <code>isSuccess</code> = true, this contains the bill identifier. If <code>isSuccess</code> = false, this contains the reason for the error.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "responseData", nulls = Nulls.SKIP)
        public _FinalStage responseData(Optional<Responsedatanonobject> responseData) {
            this.responseData = responseData;
            return this;
        }

        @java.lang.Override
        public _FinalStage isSuccess(Boolean isSuccess) {
            this.isSuccess = Optional.ofNullable(isSuccess);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "isSuccess", nulls = Nulls.SKIP)
        public _FinalStage isSuccess(Optional<Boolean> isSuccess) {
            this.isSuccess = isSuccess;
            return this;
        }

        @java.lang.Override
        public _FinalStage roomId(Long roomId) {
            this.roomId = Optional.ofNullable(roomId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "roomId", nulls = Nulls.SKIP)
        public _FinalStage roomId(Optional<Long> roomId) {
            this.roomId = roomId;
            return this;
        }

        @java.lang.Override
        public _FinalStage pageIdentifier(String pageIdentifier) {
            this.pageIdentifier = Optional.ofNullable(pageIdentifier);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "pageIdentifier", nulls = Nulls.SKIP)
        public _FinalStage pageIdentifier(Optional<String> pageIdentifier) {
            this.pageIdentifier = pageIdentifier;
            return this;
        }

        @java.lang.Override
        public _FinalStage responseCode(Integer responseCode) {
            this.responseCode = Optional.ofNullable(responseCode);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "responseCode", nulls = Nulls.SKIP)
        public _FinalStage responseCode(Optional<Integer> responseCode) {
            this.responseCode = responseCode;
            return this;
        }

        @java.lang.Override
        public BillResponse build() {
            return new BillResponse(
                    responseCode, pageIdentifier, roomId, isSuccess, responseText, responseData, additionalProperties);
        }
    }
}
