/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.resources.ocr;

import io.github.payabli.api.core.ClientOptions;
import io.github.payabli.api.core.RequestOptions;
import io.github.payabli.api.resources.ocr.requests.OcrDocumentFormRequest;
import io.github.payabli.api.resources.ocr.requests.OcrDocumentJsonRequest;
import io.github.payabli.api.types.PayabliApiResponseOcr;
import java.io.File;
import java.io.InputStream;
import java.util.concurrent.CompletableFuture;
import okhttp3.MediaType;

public class AsyncOcrClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawOcrClient rawClient;

    public AsyncOcrClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawOcrClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawOcrClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Use this endpoint to upload a document file for OCR processing as <code>multipart/form-data</code>, with the file in a field named <code>file</code>. The accepted file formats include PDF, JPG, JPEG, PNG, and GIF. Specify the desired type of result (either 'bill' or 'invoice') in the path parameter <code>typeResult</code>. The response will contain the OCR processing results, including extracted data such as bill number, vendor information, bill items, and more. To send the file as a Base64-encoded string in a JSON body instead, use <code>ocrDocumentJson</code>.
     */
    public CompletableFuture<PayabliApiResponseOcr> ocrDocumentForm(
            String typeResult, File file, OcrDocumentFormRequest request) {
        return this.rawClient.ocrDocumentForm(typeResult, file, request).thenApply(response -> response.body());
    }

    /**
     * Use this endpoint to upload a document file for OCR processing as <code>multipart/form-data</code>, with the file in a field named <code>file</code>. The accepted file formats include PDF, JPG, JPEG, PNG, and GIF. Specify the desired type of result (either 'bill' or 'invoice') in the path parameter <code>typeResult</code>. The response will contain the OCR processing results, including extracted data such as bill number, vendor information, bill items, and more. To send the file as a Base64-encoded string in a JSON body instead, use <code>ocrDocumentJson</code>.
     */
    public CompletableFuture<PayabliApiResponseOcr> ocrDocumentForm(
            String typeResult, File file, OcrDocumentFormRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .ocrDocumentForm(typeResult, file, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<PayabliApiResponseOcr> ocrDocumentForm(
            String typeResult, InputStream stream, String filename) {
        return this.rawClient.ocrDocumentForm(typeResult, stream, filename).thenApply(response -> response.body());
    }

    public CompletableFuture<PayabliApiResponseOcr> ocrDocumentForm(
            String typeResult, InputStream stream, String filename, MediaType mediaType) {
        return this.rawClient
                .ocrDocumentForm(typeResult, stream, filename, mediaType)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<PayabliApiResponseOcr> ocrDocumentForm(
            String typeResult, InputStream stream, String filename, RequestOptions requestOptions) {
        return this.rawClient
                .ocrDocumentForm(typeResult, stream, filename, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<PayabliApiResponseOcr> ocrDocumentForm(
            String typeResult,
            InputStream stream,
            String filename,
            MediaType mediaType,
            RequestOptions requestOptions) {
        return this.rawClient
                .ocrDocumentForm(typeResult, stream, filename, mediaType, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Use this endpoint to submit a Base64-encoded image file for OCR processing. The accepted file formats include PDF, JPG, JPEG, PNG, and GIF. Specify the desired type of result (either 'bill' or 'invoice') in the path parameter <code>typeResult</code>. The response will contain the OCR processing results, including extracted data such as bill number, vendor information, bill items, and more.
     */
    public CompletableFuture<PayabliApiResponseOcr> ocrDocumentJson(String typeResult) {
        return this.rawClient.ocrDocumentJson(typeResult).thenApply(response -> response.body());
    }

    /**
     * Use this endpoint to submit a Base64-encoded image file for OCR processing. The accepted file formats include PDF, JPG, JPEG, PNG, and GIF. Specify the desired type of result (either 'bill' or 'invoice') in the path parameter <code>typeResult</code>. The response will contain the OCR processing results, including extracted data such as bill number, vendor information, bill items, and more.
     */
    public CompletableFuture<PayabliApiResponseOcr> ocrDocumentJson(String typeResult, RequestOptions requestOptions) {
        return this.rawClient.ocrDocumentJson(typeResult, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Use this endpoint to submit a Base64-encoded image file for OCR processing. The accepted file formats include PDF, JPG, JPEG, PNG, and GIF. Specify the desired type of result (either 'bill' or 'invoice') in the path parameter <code>typeResult</code>. The response will contain the OCR processing results, including extracted data such as bill number, vendor information, bill items, and more.
     */
    public CompletableFuture<PayabliApiResponseOcr> ocrDocumentJson(String typeResult, OcrDocumentJsonRequest request) {
        return this.rawClient.ocrDocumentJson(typeResult, request).thenApply(response -> response.body());
    }

    /**
     * Use this endpoint to submit a Base64-encoded image file for OCR processing. The accepted file formats include PDF, JPG, JPEG, PNG, and GIF. Specify the desired type of result (either 'bill' or 'invoice') in the path parameter <code>typeResult</code>. The response will contain the OCR processing results, including extracted data such as bill number, vendor information, bill items, and more.
     */
    public CompletableFuture<PayabliApiResponseOcr> ocrDocumentJson(
            String typeResult, OcrDocumentJsonRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .ocrDocumentJson(typeResult, request, requestOptions)
                .thenApply(response -> response.body());
    }
}
