/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.resources.ocr.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PayabliApiResponseOcr.Builder.class)
public final class PayabliApiResponseOcr {
    private final boolean isSuccess;

    private final String responseText;

    private final int responseCode;

    private final Optional<OcrResponseData> responseData;

    private final Map<String, Object> additionalProperties;

    private PayabliApiResponseOcr(
            boolean isSuccess,
            String responseText,
            int responseCode,
            Optional<OcrResponseData> responseData,
            Map<String, Object> additionalProperties) {
        this.isSuccess = isSuccess;
        this.responseText = responseText;
        this.responseCode = responseCode;
        this.responseData = responseData;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("isSuccess")
    public boolean getIsSuccess() {
        return isSuccess;
    }

    @JsonProperty("responseText")
    public String getResponseText() {
        return responseText;
    }

    @JsonProperty("responseCode")
    public int getResponseCode() {
        return responseCode;
    }

    /**
     * @return Details of the OCR processing result
     */
    @JsonProperty("responseData")
    public Optional<OcrResponseData> getResponseData() {
        return responseData;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PayabliApiResponseOcr && equalTo((PayabliApiResponseOcr) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PayabliApiResponseOcr other) {
        return isSuccess == other.isSuccess
                && responseText.equals(other.responseText)
                && responseCode == other.responseCode
                && responseData.equals(other.responseData);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.isSuccess, this.responseText, this.responseCode, this.responseData);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IsSuccessStage builder() {
        return new Builder();
    }

    public interface IsSuccessStage {
        ResponseTextStage isSuccess(boolean isSuccess);

        Builder from(PayabliApiResponseOcr other);
    }

    public interface ResponseTextStage {
        ResponseCodeStage responseText(@NotNull String responseText);
    }

    public interface ResponseCodeStage {
        _FinalStage responseCode(int responseCode);
    }

    public interface _FinalStage {
        PayabliApiResponseOcr build();

        /**
         * <p>Details of the OCR processing result</p>
         */
        _FinalStage responseData(Optional<OcrResponseData> responseData);

        _FinalStage responseData(OcrResponseData responseData);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IsSuccessStage, ResponseTextStage, ResponseCodeStage, _FinalStage {
        private boolean isSuccess;

        private String responseText;

        private int responseCode;

        private Optional<OcrResponseData> responseData = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PayabliApiResponseOcr other) {
            isSuccess(other.getIsSuccess());
            responseText(other.getResponseText());
            responseCode(other.getResponseCode());
            responseData(other.getResponseData());
            return this;
        }

        @java.lang.Override
        @JsonSetter("isSuccess")
        public ResponseTextStage isSuccess(boolean isSuccess) {
            this.isSuccess = isSuccess;
            return this;
        }

        @java.lang.Override
        @JsonSetter("responseText")
        public ResponseCodeStage responseText(@NotNull String responseText) {
            this.responseText = Objects.requireNonNull(responseText, "responseText must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("responseCode")
        public _FinalStage responseCode(int responseCode) {
            this.responseCode = responseCode;
            return this;
        }

        /**
         * <p>Details of the OCR processing result</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage responseData(OcrResponseData responseData) {
            this.responseData = Optional.ofNullable(responseData);
            return this;
        }

        /**
         * <p>Details of the OCR processing result</p>
         */
        @java.lang.Override
        @JsonSetter(value = "responseData", nulls = Nulls.SKIP)
        public _FinalStage responseData(Optional<OcrResponseData> responseData) {
            this.responseData = responseData;
            return this;
        }

        @java.lang.Override
        public PayabliApiResponseOcr build() {
            return new PayabliApiResponseOcr(isSuccess, responseText, responseCode, responseData, additionalProperties);
        }
    }
}
