/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.resources.billing;

import com.fasterxml.jackson.core.JsonProcessingException;
import io.github.payabli.api.core.ClientOptions;
import io.github.payabli.api.core.EndpointMetadata;
import io.github.payabli.api.core.ObjectMappers;
import io.github.payabli.api.core.PayabliApiClientApiException;
import io.github.payabli.api.core.PayabliApiClientException;
import io.github.payabli.api.core.PayabliApiClientHttpResponse;
import io.github.payabli.api.core.QueryStringMapper;
import io.github.payabli.api.core.RequestOptions;
import io.github.payabli.api.core.RetryInterceptor;
import io.github.payabli.api.errors.BadRequestError;
import io.github.payabli.api.errors.ForbiddenError;
import io.github.payabli.api.errors.InternalServerError;
import io.github.payabli.api.errors.NotFoundError;
import io.github.payabli.api.errors.UnauthorizedError;
import io.github.payabli.api.resources.billing.requests.ListBillingProfilesRequest;
import io.github.payabli.api.resources.billing.types.GetProfileBillingRequestEntityType;
import io.github.payabli.api.resources.billing.types.GetProfileBillingRequestServiceGroup;
import io.github.payabli.api.types.BillingProfileQueryResponse;
import io.github.payabli.api.types.BillingProfileResponse;
import io.github.payabli.api.types.PayabliErrorBody;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawBillingClient {
    protected final ClientOptions clientOptions;

    public AsyncRawBillingClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns every billing profile that belongs to an organization. This is
     * the data behind the Profile Library table in the Payabli Portal.
     * <p>Requires a token with the <code>billing_profile_read</code> permission; a token
     * without it gets <code>403 Forbidden</code>.</p>
     */
    public CompletableFuture<PayabliApiClientHttpResponse<BillingProfileQueryResponse>> listProfiles(long orgId) {
        return listProfiles(orgId, ListBillingProfilesRequest.builder().build());
    }

    /**
     * Returns every billing profile that belongs to an organization. This is
     * the data behind the Profile Library table in the Payabli Portal.
     * <p>Requires a token with the <code>billing_profile_read</code> permission; a token
     * without it gets <code>403 Forbidden</code>.</p>
     */
    public CompletableFuture<PayabliApiClientHttpResponse<BillingProfileQueryResponse>> listProfiles(
            long orgId, RequestOptions requestOptions) {
        return listProfiles(orgId, ListBillingProfilesRequest.builder().build(), requestOptions);
    }

    /**
     * Returns every billing profile that belongs to an organization. This is
     * the data behind the Profile Library table in the Payabli Portal.
     * <p>Requires a token with the <code>billing_profile_read</code> permission; a token
     * without it gets <code>403 Forbidden</code>.</p>
     */
    public CompletableFuture<PayabliApiClientHttpResponse<BillingProfileQueryResponse>> listProfiles(
            long orgId, ListBillingProfilesRequest request) {
        return listProfiles(orgId, request, null);
    }

    /**
     * Returns every billing profile that belongs to an organization. This is
     * the data behind the Profile Library table in the Payabli Portal.
     * <p>Requires a token with the <code>billing_profile_read</code> permission; a token
     * without it gets <code>403 Forbidden</code>.</p>
     */
    public CompletableFuture<PayabliApiClientHttpResponse<BillingProfileQueryResponse>> listProfiles(
            long orgId, ListBillingProfilesRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("billing/configuration/org")
                .addPathSegment(Long.toString(orgId));
        if (request.getProfileName().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "profileName", request.getProfileName().get(), false);
        }
        if (request.getProfileId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "profileId", request.getProfileId().get(), false);
        }
        if (request.getLimitRecord().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limitRecord", request.getLimitRecord().get(), false);
        }
        if (request.getFromRecord().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fromRecord", request.getFromRecord().get(), false);
        }
        if (request.getFeeType().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "feeType", request.getFeeType().get(), true);
        }
        if (request.getServiceVertical().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "serviceVertical", request.getServiceVertical().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Map<String, String> _headers = new HashMap<>(clientOptions.headers(requestOptions));
        _headers.putAll(clientOptions.getAuthHeaders(EndpointMetadata.of(
                EndpointMetadata.requirement(EndpointMetadata.scheme("BearerAuth")),
                EndpointMetadata.requirement(EndpointMetadata.scheme("APIKeyAuth")))));
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(_headers))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<PayabliApiClientHttpResponse<BillingProfileQueryResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new PayabliApiClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, BillingProfileQueryResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PayabliErrorBody.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PayabliErrorBody.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PayabliApiClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new PayabliApiClientException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(
                            new PayabliApiClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PayabliApiClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Returns the billing profile currently assigned to an entity, including
     * its billable events and fee schedules. Use it to read the pricing terms
     * in effect for an organization, paypoint, template, or application.
     * <p>Requires a token with the <code>billing_profile_read</code> permission and access
     * to the requested entity; otherwise the call gets <code>403 Forbidden</code>.</p>
     * <p>If the entity exists but has no profile assigned, the call returns
     * <code>404 Not Found</code>.</p>
     */
    public CompletableFuture<PayabliApiClientHttpResponse<BillingProfileResponse>> getProfile(
            GetProfileBillingRequestServiceGroup serviceGroup,
            GetProfileBillingRequestEntityType entityType,
            long entityId) {
        return getProfile(serviceGroup, entityType, entityId, null);
    }

    /**
     * Returns the billing profile currently assigned to an entity, including
     * its billable events and fee schedules. Use it to read the pricing terms
     * in effect for an organization, paypoint, template, or application.
     * <p>Requires a token with the <code>billing_profile_read</code> permission and access
     * to the requested entity; otherwise the call gets <code>403 Forbidden</code>.</p>
     * <p>If the entity exists but has no profile assigned, the call returns
     * <code>404 Not Found</code>.</p>
     */
    public CompletableFuture<PayabliApiClientHttpResponse<BillingProfileResponse>> getProfile(
            GetProfileBillingRequestServiceGroup serviceGroup,
            GetProfileBillingRequestEntityType entityType,
            long entityId,
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("billing/configuration")
                .addPathSegment(serviceGroup.toString())
                .addPathSegment(entityType.toString())
                .addPathSegment(Long.toString(entityId));
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Map<String, String> _headers = new HashMap<>(clientOptions.headers(requestOptions));
        _headers.putAll(clientOptions.getAuthHeaders(EndpointMetadata.of(
                EndpointMetadata.requirement(EndpointMetadata.scheme("BearerAuth")),
                EndpointMetadata.requirement(EndpointMetadata.scheme("APIKeyAuth")))));
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(_headers))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<PayabliApiClientHttpResponse<BillingProfileResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new PayabliApiClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, BillingProfileResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PayabliErrorBody.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PayabliErrorBody.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PayabliApiClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new PayabliApiClientException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(
                            new PayabliApiClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PayabliApiClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
