/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payabli.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payabli.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MethodElement.Builder.class)
public final class MethodElement {
    private final Optional<Boolean> allMethodsChecked;

    private final Optional<Boolean> enabled;

    private final Optional<String> header;

    private final Optional<MethodsList> methods;

    private final Optional<Integer> order;

    private final Optional<MethodElementSettings> settings;

    private final Map<String, Object> additionalProperties;

    private MethodElement(
            Optional<Boolean> allMethodsChecked,
            Optional<Boolean> enabled,
            Optional<String> header,
            Optional<MethodsList> methods,
            Optional<Integer> order,
            Optional<MethodElementSettings> settings,
            Map<String, Object> additionalProperties) {
        this.allMethodsChecked = allMethodsChecked;
        this.enabled = enabled;
        this.header = header;
        this.methods = methods;
        this.order = order;
        this.settings = settings;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Flag indicating if all allowed payment methods will be pre-selected.
     */
    @JsonProperty("allMethodsChecked")
    public Optional<Boolean> getAllMethodsChecked() {
        return allMethodsChecked;
    }

    @JsonProperty("enabled")
    public Optional<Boolean> getEnabled() {
        return enabled;
    }

    /**
     * @return Header text for section
     */
    @JsonProperty("header")
    public Optional<String> getHeader() {
        return header;
    }

    @JsonProperty("methods")
    public Optional<MethodsList> getMethods() {
        return methods;
    }

    @JsonProperty("order")
    public Optional<Integer> getOrder() {
        return order;
    }

    /**
     * @return Settings for wallet payment methods.
     */
    @JsonProperty("settings")
    public Optional<MethodElementSettings> getSettings() {
        return settings;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MethodElement && equalTo((MethodElement) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MethodElement other) {
        return allMethodsChecked.equals(other.allMethodsChecked)
                && enabled.equals(other.enabled)
                && header.equals(other.header)
                && methods.equals(other.methods)
                && order.equals(other.order)
                && settings.equals(other.settings);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.allMethodsChecked, this.enabled, this.header, this.methods, this.order, this.settings);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> allMethodsChecked = Optional.empty();

        private Optional<Boolean> enabled = Optional.empty();

        private Optional<String> header = Optional.empty();

        private Optional<MethodsList> methods = Optional.empty();

        private Optional<Integer> order = Optional.empty();

        private Optional<MethodElementSettings> settings = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(MethodElement other) {
            allMethodsChecked(other.getAllMethodsChecked());
            enabled(other.getEnabled());
            header(other.getHeader());
            methods(other.getMethods());
            order(other.getOrder());
            settings(other.getSettings());
            return this;
        }

        /**
         * <p>Flag indicating if all allowed payment methods will be pre-selected.</p>
         */
        @JsonSetter(value = "allMethodsChecked", nulls = Nulls.SKIP)
        public Builder allMethodsChecked(Optional<Boolean> allMethodsChecked) {
            this.allMethodsChecked = allMethodsChecked;
            return this;
        }

        public Builder allMethodsChecked(Boolean allMethodsChecked) {
            this.allMethodsChecked = Optional.ofNullable(allMethodsChecked);
            return this;
        }

        @JsonSetter(value = "enabled", nulls = Nulls.SKIP)
        public Builder enabled(Optional<Boolean> enabled) {
            this.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            this.enabled = Optional.ofNullable(enabled);
            return this;
        }

        /**
         * <p>Header text for section</p>
         */
        @JsonSetter(value = "header", nulls = Nulls.SKIP)
        public Builder header(Optional<String> header) {
            this.header = header;
            return this;
        }

        public Builder header(String header) {
            this.header = Optional.ofNullable(header);
            return this;
        }

        @JsonSetter(value = "methods", nulls = Nulls.SKIP)
        public Builder methods(Optional<MethodsList> methods) {
            this.methods = methods;
            return this;
        }

        public Builder methods(MethodsList methods) {
            this.methods = Optional.ofNullable(methods);
            return this;
        }

        @JsonSetter(value = "order", nulls = Nulls.SKIP)
        public Builder order(Optional<Integer> order) {
            this.order = order;
            return this;
        }

        public Builder order(Integer order) {
            this.order = Optional.ofNullable(order);
            return this;
        }

        /**
         * <p>Settings for wallet payment methods.</p>
         */
        @JsonSetter(value = "settings", nulls = Nulls.SKIP)
        public Builder settings(Optional<MethodElementSettings> settings) {
            this.settings = settings;
            return this;
        }

        public Builder settings(MethodElementSettings settings) {
            this.settings = Optional.ofNullable(settings);
            return this;
        }

        public MethodElement build() {
            return new MethodElement(
                    allMethodsChecked, enabled, header, methods, order, settings, additionalProperties);
        }
    }
}
