/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.resources.ghostcard.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.api.core.ObjectMappers;
import io.github.payabli.api.resources.ghostcard.types.CardStatus;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateCardRequestBody.Builder.class)
public final class UpdateCardRequestBody {
    private final String cardToken;

    private final Optional<CardStatus> status;

    private final Map<String, Object> additionalProperties;

    private UpdateCardRequestBody(
            String cardToken, Optional<CardStatus> status, Map<String, Object> additionalProperties) {
        this.cardToken = cardToken;
        this.status = status;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Token that uniquely identifies the card. This is the <code>ReferenceId</code> returned when the card was created.
     */
    @JsonProperty("cardToken")
    public String getCardToken() {
        return cardToken;
    }

    /**
     * @return The new status to set on the card.
     */
    @JsonProperty("status")
    public Optional<CardStatus> getStatus() {
        return status;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateCardRequestBody && equalTo((UpdateCardRequestBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateCardRequestBody other) {
        return cardToken.equals(other.cardToken) && status.equals(other.status);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.cardToken, this.status);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CardTokenStage builder() {
        return new Builder();
    }

    public interface CardTokenStage {
        /**
         * <p>Token that uniquely identifies the card. This is the <code>ReferenceId</code> returned when the card was created.</p>
         */
        _FinalStage cardToken(@NotNull String cardToken);

        Builder from(UpdateCardRequestBody other);
    }

    public interface _FinalStage {
        UpdateCardRequestBody build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The new status to set on the card.</p>
         */
        _FinalStage status(Optional<CardStatus> status);

        _FinalStage status(CardStatus status);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CardTokenStage, _FinalStage {
        private String cardToken;

        private Optional<CardStatus> status = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UpdateCardRequestBody other) {
            cardToken(other.getCardToken());
            status(other.getStatus());
            return this;
        }

        /**
         * <p>Token that uniquely identifies the card. This is the <code>ReferenceId</code> returned when the card was created.</p>
         * <p>Token that uniquely identifies the card. This is the <code>ReferenceId</code> returned when the card was created.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("cardToken")
        public _FinalStage cardToken(@NotNull String cardToken) {
            this.cardToken = Objects.requireNonNull(cardToken, "cardToken must not be null");
            return this;
        }

        /**
         * <p>The new status to set on the card.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage status(CardStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * <p>The new status to set on the card.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public _FinalStage status(Optional<CardStatus> status) {
            this.status = status;
            return this;
        }

        @java.lang.Override
        public UpdateCardRequestBody build() {
            return new UpdateCardRequestBody(cardToken, status, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
