/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.resources.ghostcard.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateGhostCardResponse.Builder.class)
public final class CreateGhostCardResponse {
    private final Optional<Boolean> isSuccess;

    private final String responseText;

    private final Optional<CreateGhostCardResponseData> responseData;

    private final Map<String, Object> additionalProperties;

    private CreateGhostCardResponse(
            Optional<Boolean> isSuccess,
            String responseText,
            Optional<CreateGhostCardResponseData> responseData,
            Map<String, Object> additionalProperties) {
        this.isSuccess = isSuccess;
        this.responseText = responseText;
        this.responseData = responseData;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("isSuccess")
    public Optional<Boolean> getIsSuccess() {
        return isSuccess;
    }

    @JsonProperty("responseText")
    public String getResponseText() {
        return responseText;
    }

    @JsonProperty("responseData")
    public Optional<CreateGhostCardResponseData> getResponseData() {
        return responseData;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateGhostCardResponse && equalTo((CreateGhostCardResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateGhostCardResponse other) {
        return isSuccess.equals(other.isSuccess)
                && responseText.equals(other.responseText)
                && responseData.equals(other.responseData);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.isSuccess, this.responseText, this.responseData);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ResponseTextStage builder() {
        return new Builder();
    }

    public interface ResponseTextStage {
        _FinalStage responseText(@NotNull String responseText);

        Builder from(CreateGhostCardResponse other);
    }

    public interface _FinalStage {
        CreateGhostCardResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage isSuccess(Optional<Boolean> isSuccess);

        _FinalStage isSuccess(Boolean isSuccess);

        _FinalStage responseData(Optional<CreateGhostCardResponseData> responseData);

        _FinalStage responseData(CreateGhostCardResponseData responseData);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ResponseTextStage, _FinalStage {
        private String responseText;

        private Optional<CreateGhostCardResponseData> responseData = Optional.empty();

        private Optional<Boolean> isSuccess = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateGhostCardResponse other) {
            isSuccess(other.getIsSuccess());
            responseText(other.getResponseText());
            responseData(other.getResponseData());
            return this;
        }

        @java.lang.Override
        @JsonSetter("responseText")
        public _FinalStage responseText(@NotNull String responseText) {
            this.responseText = Objects.requireNonNull(responseText, "responseText must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage responseData(CreateGhostCardResponseData responseData) {
            this.responseData = Optional.ofNullable(responseData);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "responseData", nulls = Nulls.SKIP)
        public _FinalStage responseData(Optional<CreateGhostCardResponseData> responseData) {
            this.responseData = responseData;
            return this;
        }

        @java.lang.Override
        public _FinalStage isSuccess(Boolean isSuccess) {
            this.isSuccess = Optional.ofNullable(isSuccess);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "isSuccess", nulls = Nulls.SKIP)
        public _FinalStage isSuccess(Optional<Boolean> isSuccess) {
            this.isSuccess = isSuccess;
            return this;
        }

        @java.lang.Override
        public CreateGhostCardResponse build() {
            return new CreateGhostCardResponse(isSuccess, responseText, responseData, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
