/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.types;

import java.util.Optional;

public interface IAchSetup {
    Optional<Boolean> getAcceptCcd();

    Optional<Boolean> getAcceptPpd();

    Optional<Boolean> getAcceptWeb();
}
