/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum TypeAccount {
    CHECKING("Checking"),

    SAVINGS("Savings");

    private final String value;

    TypeAccount(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
