/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Whencharged {
    WHEN_SERVICE_PROVIDED("When Service Provided"),

    IN_ADVANCE("In Advance");

    private final String value;

    Whencharged(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
