/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Ach.Builder.class)
public final class Ach {
    private final String achAccount;

    private final Optional<Achaccounttype> achAccountType;

    private final Optional<String> achCode;

    private final String achHolder;

    private final Optional<AchHolderType> achHolderType;

    private final String achRouting;

    private final Optional<String> device;

    private final Map<String, Object> additionalProperties;

    private Ach(
            String achAccount,
            Optional<Achaccounttype> achAccountType,
            Optional<String> achCode,
            String achHolder,
            Optional<AchHolderType> achHolderType,
            String achRouting,
            Optional<String> device,
            Map<String, Object> additionalProperties) {
        this.achAccount = achAccount;
        this.achAccountType = achAccountType;
        this.achCode = achCode;
        this.achHolder = achHolder;
        this.achHolderType = achHolderType;
        this.achRouting = achRouting;
        this.device = device;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Bank account number. This field is <strong>required</strong> when method = <code>ach</code>.
     */
    @JsonProperty("achAccount")
    public String getAchAccount() {
        return achAccount;
    }

    /**
     * @return Bank account type. This field is <strong>required</strong> when method = <code>ach</code>.
     */
    @JsonProperty("achAccountType")
    public Optional<Achaccounttype> getAchAccountType() {
        return achAccountType;
    }

    @JsonProperty("achCode")
    public Optional<String> getAchCode() {
        return achCode;
    }

    @JsonProperty("achHolder")
    public String getAchHolder() {
        return achHolder;
    }

    @JsonProperty("achHolderType")
    public Optional<AchHolderType> getAchHolderType() {
        return achHolderType;
    }

    /**
     * @return ABA/routing number of bank account. This field is <strong>required</strong> when method is <code>ach</code>.
     */
    @JsonProperty("achRouting")
    public String getAchRouting() {
        return achRouting;
    }

    @JsonProperty("device")
    public Optional<String> getDevice() {
        return device;
    }

    @JsonProperty("method")
    public String getMethod() {
        return "ach";
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Ach && equalTo((Ach) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Ach other) {
        return achAccount.equals(other.achAccount)
                && achAccountType.equals(other.achAccountType)
                && achCode.equals(other.achCode)
                && achHolder.equals(other.achHolder)
                && achHolderType.equals(other.achHolderType)
                && achRouting.equals(other.achRouting)
                && device.equals(other.device);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.achAccount,
                this.achAccountType,
                this.achCode,
                this.achHolder,
                this.achHolderType,
                this.achRouting,
                this.device);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AchAccountStage builder() {
        return new Builder();
    }

    public interface AchAccountStage {
        /**
         * <p>Bank account number. This field is <strong>required</strong> when method = <code>ach</code>.</p>
         */
        AchHolderStage achAccount(@NotNull String achAccount);

        Builder from(Ach other);
    }

    public interface AchHolderStage {
        AchRoutingStage achHolder(@NotNull String achHolder);
    }

    public interface AchRoutingStage {
        /**
         * <p>ABA/routing number of bank account. This field is <strong>required</strong> when method is <code>ach</code>.</p>
         */
        _FinalStage achRouting(@NotNull String achRouting);
    }

    public interface _FinalStage {
        Ach build();

        /**
         * <p>Bank account type. This field is <strong>required</strong> when method = <code>ach</code>.</p>
         */
        _FinalStage achAccountType(Optional<Achaccounttype> achAccountType);

        _FinalStage achAccountType(Achaccounttype achAccountType);

        _FinalStage achCode(Optional<String> achCode);

        _FinalStage achCode(String achCode);

        _FinalStage achHolderType(Optional<AchHolderType> achHolderType);

        _FinalStage achHolderType(AchHolderType achHolderType);

        _FinalStage device(Optional<String> device);

        _FinalStage device(String device);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AchAccountStage, AchHolderStage, AchRoutingStage, _FinalStage {
        private String achAccount;

        private String achHolder;

        private String achRouting;

        private Optional<String> device = Optional.empty();

        private Optional<AchHolderType> achHolderType = Optional.empty();

        private Optional<String> achCode = Optional.empty();

        private Optional<Achaccounttype> achAccountType = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Ach other) {
            achAccount(other.getAchAccount());
            achAccountType(other.getAchAccountType());
            achCode(other.getAchCode());
            achHolder(other.getAchHolder());
            achHolderType(other.getAchHolderType());
            achRouting(other.getAchRouting());
            device(other.getDevice());
            return this;
        }

        /**
         * <p>Bank account number. This field is <strong>required</strong> when method = <code>ach</code>.</p>
         * <p>Bank account number. This field is <strong>required</strong> when method = <code>ach</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("achAccount")
        public AchHolderStage achAccount(@NotNull String achAccount) {
            this.achAccount = Objects.requireNonNull(achAccount, "achAccount must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("achHolder")
        public AchRoutingStage achHolder(@NotNull String achHolder) {
            this.achHolder = Objects.requireNonNull(achHolder, "achHolder must not be null");
            return this;
        }

        /**
         * <p>ABA/routing number of bank account. This field is <strong>required</strong> when method is <code>ach</code>.</p>
         * <p>ABA/routing number of bank account. This field is <strong>required</strong> when method is <code>ach</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("achRouting")
        public _FinalStage achRouting(@NotNull String achRouting) {
            this.achRouting = Objects.requireNonNull(achRouting, "achRouting must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage device(String device) {
            this.device = Optional.ofNullable(device);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "device", nulls = Nulls.SKIP)
        public _FinalStage device(Optional<String> device) {
            this.device = device;
            return this;
        }

        @java.lang.Override
        public _FinalStage achHolderType(AchHolderType achHolderType) {
            this.achHolderType = Optional.ofNullable(achHolderType);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "achHolderType", nulls = Nulls.SKIP)
        public _FinalStage achHolderType(Optional<AchHolderType> achHolderType) {
            this.achHolderType = achHolderType;
            return this;
        }

        @java.lang.Override
        public _FinalStage achCode(String achCode) {
            this.achCode = Optional.ofNullable(achCode);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "achCode", nulls = Nulls.SKIP)
        public _FinalStage achCode(Optional<String> achCode) {
            this.achCode = achCode;
            return this;
        }

        /**
         * <p>Bank account type. This field is <strong>required</strong> when method = <code>ach</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage achAccountType(Achaccounttype achAccountType) {
            this.achAccountType = Optional.ofNullable(achAccountType);
            return this;
        }

        /**
         * <p>Bank account type. This field is <strong>required</strong> when method = <code>ach</code>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "achAccountType", nulls = Nulls.SKIP)
        public _FinalStage achAccountType(Optional<Achaccounttype> achAccountType) {
            this.achAccountType = achAccountType;
            return this;
        }

        @java.lang.Override
        public Ach build() {
            return new Ach(
                    achAccount,
                    achAccountType,
                    achCode,
                    achHolder,
                    achHolderType,
                    achRouting,
                    device,
                    additionalProperties);
        }
    }
}
