/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.api.core.Nullable;
import io.github.payabli.api.core.NullableNonemptyFilter;
import io.github.payabli.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BillPayOutData.Builder.class)
public final class BillPayOutData {
    private final Optional<Long> billId;

    private final Optional<String> lotNumber;

    private final Optional<String> accountingField1;

    private final Optional<String> accountingField2;

    private final Optional<Terms> terms;

    private final Optional<String> additionalData;

    private final Optional<List<FileContent>> attachments;

    private final Optional<String> invoiceNumber;

    private final Optional<String> netAmount;

    private final Optional<String> invoiceDate;

    private final Optional<String> dueDate;

    private final Optional<String> comments;

    private final Optional<String> identifier;

    private final Optional<String> discount;

    private final Optional<String> totalAmount;

    private final Map<String, Object> additionalProperties;

    private BillPayOutData(
            Optional<Long> billId,
            Optional<String> lotNumber,
            Optional<String> accountingField1,
            Optional<String> accountingField2,
            Optional<Terms> terms,
            Optional<String> additionalData,
            Optional<List<FileContent>> attachments,
            Optional<String> invoiceNumber,
            Optional<String> netAmount,
            Optional<String> invoiceDate,
            Optional<String> dueDate,
            Optional<String> comments,
            Optional<String> identifier,
            Optional<String> discount,
            Optional<String> totalAmount,
            Map<String, Object> additionalProperties) {
        this.billId = billId;
        this.lotNumber = lotNumber;
        this.accountingField1 = accountingField1;
        this.accountingField2 = accountingField2;
        this.terms = terms;
        this.additionalData = additionalData;
        this.attachments = attachments;
        this.invoiceNumber = invoiceNumber;
        this.netAmount = netAmount;
        this.invoiceDate = invoiceDate;
        this.dueDate = dueDate;
        this.comments = comments;
        this.identifier = identifier;
        this.discount = discount;
        this.totalAmount = totalAmount;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Bill ID in Payabli.
     */
    @JsonProperty("billId")
    public Optional<Long> getBillId() {
        return billId;
    }

    /**
     * @return Lot number associated with the bill.
     */
    @JsonIgnore
    public Optional<String> getLotNumber() {
        if (lotNumber == null) {
            return Optional.empty();
        }
        return lotNumber;
    }

    @JsonProperty("AccountingField1")
    public Optional<String> getAccountingField1() {
        return accountingField1;
    }

    @JsonProperty("AccountingField2")
    public Optional<String> getAccountingField2() {
        return accountingField2;
    }

    /**
     * @return Description of payment terms.
     */
    @JsonProperty("Terms")
    public Optional<Terms> getTerms() {
        return terms;
    }

    @JsonProperty("AdditionalData")
    public Optional<String> getAdditionalData() {
        return additionalData;
    }

    /**
     * @return Bill image attachment. Send the bill image as Base64-encoded string, or as a publicly accessible link. For full details on using this field with a payout authorization, see <a href="/developers/developer-guides/pay-out-manage-payouts">the documentation</a>.
     */
    @JsonProperty("attachments")
    public Optional<List<FileContent>> getAttachments() {
        return attachments;
    }

    /**
     * @return Custom number identifying the bill. Must be unique in paypoint. <strong>Required</strong> for new bill and when <code>billId</code> isn't provided.
     */
    @JsonProperty("invoiceNumber")
    public Optional<String> getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * @return Net Amount owed in bill. Required when adding a bill.
     */
    @JsonProperty("netAmount")
    public Optional<String> getNetAmount() {
        return netAmount;
    }

    /**
     * @return Bill date in format YYYY-MM-DD or MM/DD/YYYY.
     */
    @JsonIgnore
    public Optional<String> getInvoiceDate() {
        if (invoiceDate == null) {
            return Optional.empty();
        }
        return invoiceDate;
    }

    /**
     * @return Bill due date in format YYYY-MM-DD or MM/DD/YYYY.
     */
    @JsonIgnore
    public Optional<String> getDueDate() {
        if (dueDate == null) {
            return Optional.empty();
        }
        return dueDate;
    }

    /**
     * @return Any comments about bill. <strong>For managed payouts, this field has a limit of 100 characters</strong>.
     */
    @JsonProperty("comments")
    public Optional<String> getComments() {
        return comments;
    }

    /**
     * @return Custom identifier for the bill.
     */
    @JsonIgnore
    public Optional<String> getIdentifier() {
        if (identifier == null) {
            return Optional.empty();
        }
        return identifier;
    }

    /**
     * @return Bill discount amount.
     */
    @JsonProperty("discount")
    public Optional<String> getDiscount() {
        return discount;
    }

    /**
     * @return Total amount of the bill.
     */
    @JsonIgnore
    public Optional<String> getTotalAmount() {
        if (totalAmount == null) {
            return Optional.empty();
        }
        return totalAmount;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("LotNumber")
    private Optional<String> _getLotNumber() {
        return lotNumber;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("invoiceDate")
    private Optional<String> _getInvoiceDate() {
        return invoiceDate;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("dueDate")
    private Optional<String> _getDueDate() {
        return dueDate;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("identifier")
    private Optional<String> _getIdentifier() {
        return identifier;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("totalAmount")
    private Optional<String> _getTotalAmount() {
        return totalAmount;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BillPayOutData && equalTo((BillPayOutData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BillPayOutData other) {
        return billId.equals(other.billId)
                && lotNumber.equals(other.lotNumber)
                && accountingField1.equals(other.accountingField1)
                && accountingField2.equals(other.accountingField2)
                && terms.equals(other.terms)
                && additionalData.equals(other.additionalData)
                && attachments.equals(other.attachments)
                && invoiceNumber.equals(other.invoiceNumber)
                && netAmount.equals(other.netAmount)
                && invoiceDate.equals(other.invoiceDate)
                && dueDate.equals(other.dueDate)
                && comments.equals(other.comments)
                && identifier.equals(other.identifier)
                && discount.equals(other.discount)
                && totalAmount.equals(other.totalAmount);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.billId,
                this.lotNumber,
                this.accountingField1,
                this.accountingField2,
                this.terms,
                this.additionalData,
                this.attachments,
                this.invoiceNumber,
                this.netAmount,
                this.invoiceDate,
                this.dueDate,
                this.comments,
                this.identifier,
                this.discount,
                this.totalAmount);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Long> billId = Optional.empty();

        private Optional<String> lotNumber = Optional.empty();

        private Optional<String> accountingField1 = Optional.empty();

        private Optional<String> accountingField2 = Optional.empty();

        private Optional<Terms> terms = Optional.empty();

        private Optional<String> additionalData = Optional.empty();

        private Optional<List<FileContent>> attachments = Optional.empty();

        private Optional<String> invoiceNumber = Optional.empty();

        private Optional<String> netAmount = Optional.empty();

        private Optional<String> invoiceDate = Optional.empty();

        private Optional<String> dueDate = Optional.empty();

        private Optional<String> comments = Optional.empty();

        private Optional<String> identifier = Optional.empty();

        private Optional<String> discount = Optional.empty();

        private Optional<String> totalAmount = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BillPayOutData other) {
            billId(other.getBillId());
            lotNumber(other.getLotNumber());
            accountingField1(other.getAccountingField1());
            accountingField2(other.getAccountingField2());
            terms(other.getTerms());
            additionalData(other.getAdditionalData());
            attachments(other.getAttachments());
            invoiceNumber(other.getInvoiceNumber());
            netAmount(other.getNetAmount());
            invoiceDate(other.getInvoiceDate());
            dueDate(other.getDueDate());
            comments(other.getComments());
            identifier(other.getIdentifier());
            discount(other.getDiscount());
            totalAmount(other.getTotalAmount());
            return this;
        }

        /**
         * <p>Bill ID in Payabli.</p>
         */
        @JsonSetter(value = "billId", nulls = Nulls.SKIP)
        public Builder billId(Optional<Long> billId) {
            this.billId = billId;
            return this;
        }

        public Builder billId(Long billId) {
            this.billId = Optional.ofNullable(billId);
            return this;
        }

        /**
         * <p>Lot number associated with the bill.</p>
         */
        @JsonSetter(value = "LotNumber", nulls = Nulls.SKIP)
        public Builder lotNumber(Optional<String> lotNumber) {
            this.lotNumber = lotNumber;
            return this;
        }

        public Builder lotNumber(String lotNumber) {
            this.lotNumber = Optional.ofNullable(lotNumber);
            return this;
        }

        public Builder lotNumber(Nullable<String> lotNumber) {
            if (lotNumber.isNull()) {
                this.lotNumber = null;
            } else if (lotNumber.isEmpty()) {
                this.lotNumber = Optional.empty();
            } else {
                this.lotNumber = Optional.of(lotNumber.get());
            }
            return this;
        }

        @JsonSetter(value = "AccountingField1", nulls = Nulls.SKIP)
        public Builder accountingField1(Optional<String> accountingField1) {
            this.accountingField1 = accountingField1;
            return this;
        }

        public Builder accountingField1(String accountingField1) {
            this.accountingField1 = Optional.ofNullable(accountingField1);
            return this;
        }

        @JsonSetter(value = "AccountingField2", nulls = Nulls.SKIP)
        public Builder accountingField2(Optional<String> accountingField2) {
            this.accountingField2 = accountingField2;
            return this;
        }

        public Builder accountingField2(String accountingField2) {
            this.accountingField2 = Optional.ofNullable(accountingField2);
            return this;
        }

        /**
         * <p>Description of payment terms.</p>
         */
        @JsonSetter(value = "Terms", nulls = Nulls.SKIP)
        public Builder terms(Optional<Terms> terms) {
            this.terms = terms;
            return this;
        }

        public Builder terms(Terms terms) {
            this.terms = Optional.ofNullable(terms);
            return this;
        }

        @JsonSetter(value = "AdditionalData", nulls = Nulls.SKIP)
        public Builder additionalData(Optional<String> additionalData) {
            this.additionalData = additionalData;
            return this;
        }

        public Builder additionalData(String additionalData) {
            this.additionalData = Optional.ofNullable(additionalData);
            return this;
        }

        /**
         * <p>Bill image attachment. Send the bill image as Base64-encoded string, or as a publicly accessible link. For full details on using this field with a payout authorization, see <a href="/developers/developer-guides/pay-out-manage-payouts">the documentation</a>.</p>
         */
        @JsonSetter(value = "attachments", nulls = Nulls.SKIP)
        public Builder attachments(Optional<List<FileContent>> attachments) {
            this.attachments = attachments;
            return this;
        }

        public Builder attachments(List<FileContent> attachments) {
            this.attachments = Optional.ofNullable(attachments);
            return this;
        }

        /**
         * <p>Custom number identifying the bill. Must be unique in paypoint. <strong>Required</strong> for new bill and when <code>billId</code> isn't provided.</p>
         */
        @JsonSetter(value = "invoiceNumber", nulls = Nulls.SKIP)
        public Builder invoiceNumber(Optional<String> invoiceNumber) {
            this.invoiceNumber = invoiceNumber;
            return this;
        }

        public Builder invoiceNumber(String invoiceNumber) {
            this.invoiceNumber = Optional.ofNullable(invoiceNumber);
            return this;
        }

        /**
         * <p>Net Amount owed in bill. Required when adding a bill.</p>
         */
        @JsonSetter(value = "netAmount", nulls = Nulls.SKIP)
        public Builder netAmount(Optional<String> netAmount) {
            this.netAmount = netAmount;
            return this;
        }

        public Builder netAmount(String netAmount) {
            this.netAmount = Optional.ofNullable(netAmount);
            return this;
        }

        /**
         * <p>Bill date in format YYYY-MM-DD or MM/DD/YYYY.</p>
         */
        @JsonSetter(value = "invoiceDate", nulls = Nulls.SKIP)
        public Builder invoiceDate(Optional<String> invoiceDate) {
            this.invoiceDate = invoiceDate;
            return this;
        }

        public Builder invoiceDate(String invoiceDate) {
            this.invoiceDate = Optional.ofNullable(invoiceDate);
            return this;
        }

        public Builder invoiceDate(Nullable<String> invoiceDate) {
            if (invoiceDate.isNull()) {
                this.invoiceDate = null;
            } else if (invoiceDate.isEmpty()) {
                this.invoiceDate = Optional.empty();
            } else {
                this.invoiceDate = Optional.of(invoiceDate.get());
            }
            return this;
        }

        /**
         * <p>Bill due date in format YYYY-MM-DD or MM/DD/YYYY.</p>
         */
        @JsonSetter(value = "dueDate", nulls = Nulls.SKIP)
        public Builder dueDate(Optional<String> dueDate) {
            this.dueDate = dueDate;
            return this;
        }

        public Builder dueDate(String dueDate) {
            this.dueDate = Optional.ofNullable(dueDate);
            return this;
        }

        public Builder dueDate(Nullable<String> dueDate) {
            if (dueDate.isNull()) {
                this.dueDate = null;
            } else if (dueDate.isEmpty()) {
                this.dueDate = Optional.empty();
            } else {
                this.dueDate = Optional.of(dueDate.get());
            }
            return this;
        }

        /**
         * <p>Any comments about bill. <strong>For managed payouts, this field has a limit of 100 characters</strong>.</p>
         */
        @JsonSetter(value = "comments", nulls = Nulls.SKIP)
        public Builder comments(Optional<String> comments) {
            this.comments = comments;
            return this;
        }

        public Builder comments(String comments) {
            this.comments = Optional.ofNullable(comments);
            return this;
        }

        /**
         * <p>Custom identifier for the bill.</p>
         */
        @JsonSetter(value = "identifier", nulls = Nulls.SKIP)
        public Builder identifier(Optional<String> identifier) {
            this.identifier = identifier;
            return this;
        }

        public Builder identifier(String identifier) {
            this.identifier = Optional.ofNullable(identifier);
            return this;
        }

        public Builder identifier(Nullable<String> identifier) {
            if (identifier.isNull()) {
                this.identifier = null;
            } else if (identifier.isEmpty()) {
                this.identifier = Optional.empty();
            } else {
                this.identifier = Optional.of(identifier.get());
            }
            return this;
        }

        /**
         * <p>Bill discount amount.</p>
         */
        @JsonSetter(value = "discount", nulls = Nulls.SKIP)
        public Builder discount(Optional<String> discount) {
            this.discount = discount;
            return this;
        }

        public Builder discount(String discount) {
            this.discount = Optional.ofNullable(discount);
            return this;
        }

        /**
         * <p>Total amount of the bill.</p>
         */
        @JsonSetter(value = "totalAmount", nulls = Nulls.SKIP)
        public Builder totalAmount(Optional<String> totalAmount) {
            this.totalAmount = totalAmount;
            return this;
        }

        public Builder totalAmount(String totalAmount) {
            this.totalAmount = Optional.ofNullable(totalAmount);
            return this;
        }

        public Builder totalAmount(Nullable<String> totalAmount) {
            if (totalAmount.isNull()) {
                this.totalAmount = null;
            } else if (totalAmount.isEmpty()) {
                this.totalAmount = Optional.empty();
            } else {
                this.totalAmount = Optional.of(totalAmount.get());
            }
            return this;
        }

        public BillPayOutData build() {
            return new BillPayOutData(
                    billId,
                    lotNumber,
                    accountingField1,
                    accountingField2,
                    terms,
                    additionalData,
                    attachments,
                    invoiceNumber,
                    netAmount,
                    invoiceDate,
                    dueDate,
                    comments,
                    identifier,
                    discount,
                    totalAmount,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
