/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConfigureApplePayOrganizationApiResponse.Builder.class)
public final class ConfigureApplePayOrganizationApiResponse {
    private final Optional<Boolean> isSuccess;

    private final Optional<String> pageIdentifier;

    private final Optional<Integer> responseCode;

    private final Optional<ApplePayOrganizationUpdateData> responseData;

    private final String responseText;

    private final Map<String, Object> additionalProperties;

    private ConfigureApplePayOrganizationApiResponse(
            Optional<Boolean> isSuccess,
            Optional<String> pageIdentifier,
            Optional<Integer> responseCode,
            Optional<ApplePayOrganizationUpdateData> responseData,
            String responseText,
            Map<String, Object> additionalProperties) {
        this.isSuccess = isSuccess;
        this.pageIdentifier = pageIdentifier;
        this.responseCode = responseCode;
        this.responseData = responseData;
        this.responseText = responseText;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("isSuccess")
    public Optional<Boolean> getIsSuccess() {
        return isSuccess;
    }

    @JsonProperty("pageIdentifier")
    public Optional<String> getPageIdentifier() {
        return pageIdentifier;
    }

    @JsonProperty("responseCode")
    public Optional<Integer> getResponseCode() {
        return responseCode;
    }

    @JsonProperty("responseData")
    public Optional<ApplePayOrganizationUpdateData> getResponseData() {
        return responseData;
    }

    @JsonProperty("responseText")
    public String getResponseText() {
        return responseText;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConfigureApplePayOrganizationApiResponse
                && equalTo((ConfigureApplePayOrganizationApiResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConfigureApplePayOrganizationApiResponse other) {
        return isSuccess.equals(other.isSuccess)
                && pageIdentifier.equals(other.pageIdentifier)
                && responseCode.equals(other.responseCode)
                && responseData.equals(other.responseData)
                && responseText.equals(other.responseText);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.isSuccess, this.pageIdentifier, this.responseCode, this.responseData, this.responseText);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ResponseTextStage builder() {
        return new Builder();
    }

    public interface ResponseTextStage {
        _FinalStage responseText(@NotNull String responseText);

        Builder from(ConfigureApplePayOrganizationApiResponse other);
    }

    public interface _FinalStage {
        ConfigureApplePayOrganizationApiResponse build();

        _FinalStage isSuccess(Optional<Boolean> isSuccess);

        _FinalStage isSuccess(Boolean isSuccess);

        _FinalStage pageIdentifier(Optional<String> pageIdentifier);

        _FinalStage pageIdentifier(String pageIdentifier);

        _FinalStage responseCode(Optional<Integer> responseCode);

        _FinalStage responseCode(Integer responseCode);

        _FinalStage responseData(Optional<ApplePayOrganizationUpdateData> responseData);

        _FinalStage responseData(ApplePayOrganizationUpdateData responseData);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ResponseTextStage, _FinalStage {
        private String responseText;

        private Optional<ApplePayOrganizationUpdateData> responseData = Optional.empty();

        private Optional<Integer> responseCode = Optional.empty();

        private Optional<String> pageIdentifier = Optional.empty();

        private Optional<Boolean> isSuccess = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ConfigureApplePayOrganizationApiResponse other) {
            isSuccess(other.getIsSuccess());
            pageIdentifier(other.getPageIdentifier());
            responseCode(other.getResponseCode());
            responseData(other.getResponseData());
            responseText(other.getResponseText());
            return this;
        }

        @java.lang.Override
        @JsonSetter("responseText")
        public _FinalStage responseText(@NotNull String responseText) {
            this.responseText = Objects.requireNonNull(responseText, "responseText must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage responseData(ApplePayOrganizationUpdateData responseData) {
            this.responseData = Optional.ofNullable(responseData);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "responseData", nulls = Nulls.SKIP)
        public _FinalStage responseData(Optional<ApplePayOrganizationUpdateData> responseData) {
            this.responseData = responseData;
            return this;
        }

        @java.lang.Override
        public _FinalStage responseCode(Integer responseCode) {
            this.responseCode = Optional.ofNullable(responseCode);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "responseCode", nulls = Nulls.SKIP)
        public _FinalStage responseCode(Optional<Integer> responseCode) {
            this.responseCode = responseCode;
            return this;
        }

        @java.lang.Override
        public _FinalStage pageIdentifier(String pageIdentifier) {
            this.pageIdentifier = Optional.ofNullable(pageIdentifier);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "pageIdentifier", nulls = Nulls.SKIP)
        public _FinalStage pageIdentifier(Optional<String> pageIdentifier) {
            this.pageIdentifier = pageIdentifier;
            return this;
        }

        @java.lang.Override
        public _FinalStage isSuccess(Boolean isSuccess) {
            this.isSuccess = Optional.ofNullable(isSuccess);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "isSuccess", nulls = Nulls.SKIP)
        public _FinalStage isSuccess(Optional<Boolean> isSuccess) {
            this.isSuccess = isSuccess;
            return this;
        }

        @java.lang.Override
        public ConfigureApplePayOrganizationApiResponse build() {
            return new ConfigureApplePayOrganizationApiResponse(
                    isSuccess, pageIdentifier, responseCode, responseData, responseText, additionalProperties);
        }
    }
}
