/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PayMethodCloudMethod {
    public static final PayMethodCloudMethod CLOUD = new PayMethodCloudMethod(Value.CLOUD, "cloud");

    private final Value value;

    private final String string;

    PayMethodCloudMethod(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PayMethodCloudMethod && this.string.equals(((PayMethodCloudMethod) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CLOUD:
                return visitor.visitCloud();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PayMethodCloudMethod valueOf(String value) {
        switch (value) {
            case "cloud":
                return CLOUD;
            default:
                return new PayMethodCloudMethod(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CLOUD,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCloud();

        T visitUnknown(String unknownType);
    }
}
