/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TapToPayActivationChallengeErrorResponse.Builder.class)
public final class TapToPayActivationChallengeErrorResponse {
    private final boolean isSuccess;

    private final String responseText;

    private final TapToPayActivationChallengeErrorResponseResponseData responseData;

    private final Map<String, Object> additionalProperties;

    private TapToPayActivationChallengeErrorResponse(
            boolean isSuccess,
            String responseText,
            TapToPayActivationChallengeErrorResponseResponseData responseData,
            Map<String, Object> additionalProperties) {
        this.isSuccess = isSuccess;
        this.responseText = responseText;
        this.responseData = responseData;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("isSuccess")
    public boolean getIsSuccess() {
        return isSuccess;
    }

    @JsonProperty("responseText")
    public String getResponseText() {
        return responseText;
    }

    @JsonProperty("responseData")
    public TapToPayActivationChallengeErrorResponseResponseData getResponseData() {
        return responseData;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TapToPayActivationChallengeErrorResponse
                && equalTo((TapToPayActivationChallengeErrorResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TapToPayActivationChallengeErrorResponse other) {
        return isSuccess == other.isSuccess
                && responseText.equals(other.responseText)
                && responseData.equals(other.responseData);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.isSuccess, this.responseText, this.responseData);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IsSuccessStage builder() {
        return new Builder();
    }

    public interface IsSuccessStage {
        ResponseTextStage isSuccess(boolean isSuccess);

        Builder from(TapToPayActivationChallengeErrorResponse other);
    }

    public interface ResponseTextStage {
        ResponseDataStage responseText(@NotNull String responseText);
    }

    public interface ResponseDataStage {
        _FinalStage responseData(@NotNull TapToPayActivationChallengeErrorResponseResponseData responseData);
    }

    public interface _FinalStage {
        TapToPayActivationChallengeErrorResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IsSuccessStage, ResponseTextStage, ResponseDataStage, _FinalStage {
        private boolean isSuccess;

        private String responseText;

        private TapToPayActivationChallengeErrorResponseResponseData responseData;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TapToPayActivationChallengeErrorResponse other) {
            isSuccess(other.getIsSuccess());
            responseText(other.getResponseText());
            responseData(other.getResponseData());
            return this;
        }

        @java.lang.Override
        @JsonSetter("isSuccess")
        public ResponseTextStage isSuccess(boolean isSuccess) {
            this.isSuccess = isSuccess;
            return this;
        }

        @java.lang.Override
        @JsonSetter("responseText")
        public ResponseDataStage responseText(@NotNull String responseText) {
            this.responseText = Objects.requireNonNull(responseText, "responseText must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("responseData")
        public _FinalStage responseData(@NotNull TapToPayActivationChallengeErrorResponseResponseData responseData) {
            this.responseData = Objects.requireNonNull(responseData, "responseData must not be null");
            return this;
        }

        @java.lang.Override
        public TapToPayActivationChallengeErrorResponse build() {
            return new TapToPayActivationChallengeErrorResponse(
                    isSuccess, responseText, responseData, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
