/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.core;

public final class Environment {
    public static final Environment SANDBOX = new Environment("https://api-sandbox.payabli.com/api");

    public static final Environment PRODUCTION = new Environment("https://api.payabli.com/api");

    private final String url;

    private Environment(String url) {
        this.url = url;
    }

    public String getUrl() {
        return this.url;
    }

    public static Environment custom(String url) {
        return new Environment(url);
    }
}
