/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.api.resources.tokenstorage.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.api.core.ObjectMappers;
import io.github.payabli.api.types.RequestTokenStorage;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AddMethodRequest.Builder.class)
public final class AddMethodRequest {
    private final Optional<String> idempotencyKey;

    private final Optional<Boolean> achValidation;

    private final Optional<Boolean> createAnonymous;

    private final Optional<Boolean> forceCustomerCreation;

    private final Optional<Boolean> temporary;

    private final RequestTokenStorage body;

    private final Map<String, Object> additionalProperties;

    private AddMethodRequest(
            Optional<String> idempotencyKey,
            Optional<Boolean> achValidation,
            Optional<Boolean> createAnonymous,
            Optional<Boolean> forceCustomerCreation,
            Optional<Boolean> temporary,
            RequestTokenStorage body,
            Map<String, Object> additionalProperties) {
        this.idempotencyKey = idempotencyKey;
        this.achValidation = achValidation;
        this.createAnonymous = createAnonymous;
        this.forceCustomerCreation = forceCustomerCreation;
        this.temporary = temporary;
        this.body = body;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return <em>Optional but recommended</em> A unique ID that you can include to prevent duplicating objects or transactions in the case that a request is sent more than once. This key isn't generated in Payabli, you must generate it yourself. This key persists for 2 minutes. After 2 minutes, you can reuse the key if needed.
     */
    @JsonIgnore
    public Optional<String> getIdempotencyKey() {
        return idempotencyKey;
    }

    /**
     * @return When <code>true</code>, enables real-time validation of ACH account and routing numbers. This is an add-on feature, contact Payabli for more information.
     */
    @JsonProperty("achValidation")
    public Optional<Boolean> getAchValidation() {
        return achValidation;
    }

    /**
     * @return When <code>true</code>, creates a saved method with no associated customer information. The token will be associated with customer information the first time it's used to make a payment. Defaults to <code>false</code>.
     */
    @JsonProperty("createAnonymous")
    public Optional<Boolean> getCreateAnonymous() {
        return createAnonymous;
    }

    /**
     * @return When <code>true</code>, the request creates a new customer record, regardless of whether customer identifiers match an existing customer. Defaults to <code>false</code>.
     */
    @JsonProperty("forceCustomerCreation")
    public Optional<Boolean> getForceCustomerCreation() {
        return forceCustomerCreation;
    }

    /**
     * @return Creates a temporary, one-time-use token for the payment method that expires in 12 hours. Defaults to <code>false</code>.
     */
    @JsonProperty("temporary")
    public Optional<Boolean> getTemporary() {
        return temporary;
    }

    @JsonProperty("body")
    public RequestTokenStorage getBody() {
        return body;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AddMethodRequest && equalTo((AddMethodRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AddMethodRequest other) {
        return idempotencyKey.equals(other.idempotencyKey)
                && achValidation.equals(other.achValidation)
                && createAnonymous.equals(other.createAnonymous)
                && forceCustomerCreation.equals(other.forceCustomerCreation)
                && temporary.equals(other.temporary)
                && body.equals(other.body);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.idempotencyKey,
                this.achValidation,
                this.createAnonymous,
                this.forceCustomerCreation,
                this.temporary,
                this.body);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static BodyStage builder() {
        return new Builder();
    }

    public interface BodyStage {
        _FinalStage body(@NotNull RequestTokenStorage body);

        Builder from(AddMethodRequest other);
    }

    public interface _FinalStage {
        AddMethodRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p><em>Optional but recommended</em> A unique ID that you can include to prevent duplicating objects or transactions in the case that a request is sent more than once. This key isn't generated in Payabli, you must generate it yourself. This key persists for 2 minutes. After 2 minutes, you can reuse the key if needed.</p>
         */
        _FinalStage idempotencyKey(Optional<String> idempotencyKey);

        _FinalStage idempotencyKey(String idempotencyKey);

        /**
         * <p>When <code>true</code>, enables real-time validation of ACH account and routing numbers. This is an add-on feature, contact Payabli for more information.</p>
         */
        _FinalStage achValidation(Optional<Boolean> achValidation);

        _FinalStage achValidation(Boolean achValidation);

        /**
         * <p>When <code>true</code>, creates a saved method with no associated customer information. The token will be associated with customer information the first time it's used to make a payment. Defaults to <code>false</code>.</p>
         */
        _FinalStage createAnonymous(Optional<Boolean> createAnonymous);

        _FinalStage createAnonymous(Boolean createAnonymous);

        /**
         * <p>When <code>true</code>, the request creates a new customer record, regardless of whether customer identifiers match an existing customer. Defaults to <code>false</code>.</p>
         */
        _FinalStage forceCustomerCreation(Optional<Boolean> forceCustomerCreation);

        _FinalStage forceCustomerCreation(Boolean forceCustomerCreation);

        /**
         * <p>Creates a temporary, one-time-use token for the payment method that expires in 12 hours. Defaults to <code>false</code>.</p>
         */
        _FinalStage temporary(Optional<Boolean> temporary);

        _FinalStage temporary(Boolean temporary);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements BodyStage, _FinalStage {
        private RequestTokenStorage body;

        private Optional<Boolean> temporary = Optional.empty();

        private Optional<Boolean> forceCustomerCreation = Optional.empty();

        private Optional<Boolean> createAnonymous = Optional.empty();

        private Optional<Boolean> achValidation = Optional.empty();

        private Optional<String> idempotencyKey = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AddMethodRequest other) {
            idempotencyKey(other.getIdempotencyKey());
            achValidation(other.getAchValidation());
            createAnonymous(other.getCreateAnonymous());
            forceCustomerCreation(other.getForceCustomerCreation());
            temporary(other.getTemporary());
            body(other.getBody());
            return this;
        }

        @java.lang.Override
        @JsonSetter("body")
        public _FinalStage body(@NotNull RequestTokenStorage body) {
            this.body = Objects.requireNonNull(body, "body must not be null");
            return this;
        }

        /**
         * <p>Creates a temporary, one-time-use token for the payment method that expires in 12 hours. Defaults to <code>false</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage temporary(Boolean temporary) {
            this.temporary = Optional.ofNullable(temporary);
            return this;
        }

        /**
         * <p>Creates a temporary, one-time-use token for the payment method that expires in 12 hours. Defaults to <code>false</code>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "temporary", nulls = Nulls.SKIP)
        public _FinalStage temporary(Optional<Boolean> temporary) {
            this.temporary = temporary;
            return this;
        }

        /**
         * <p>When <code>true</code>, the request creates a new customer record, regardless of whether customer identifiers match an existing customer. Defaults to <code>false</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage forceCustomerCreation(Boolean forceCustomerCreation) {
            this.forceCustomerCreation = Optional.ofNullable(forceCustomerCreation);
            return this;
        }

        /**
         * <p>When <code>true</code>, the request creates a new customer record, regardless of whether customer identifiers match an existing customer. Defaults to <code>false</code>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "forceCustomerCreation", nulls = Nulls.SKIP)
        public _FinalStage forceCustomerCreation(Optional<Boolean> forceCustomerCreation) {
            this.forceCustomerCreation = forceCustomerCreation;
            return this;
        }

        /**
         * <p>When <code>true</code>, creates a saved method with no associated customer information. The token will be associated with customer information the first time it's used to make a payment. Defaults to <code>false</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage createAnonymous(Boolean createAnonymous) {
            this.createAnonymous = Optional.ofNullable(createAnonymous);
            return this;
        }

        /**
         * <p>When <code>true</code>, creates a saved method with no associated customer information. The token will be associated with customer information the first time it's used to make a payment. Defaults to <code>false</code>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "createAnonymous", nulls = Nulls.SKIP)
        public _FinalStage createAnonymous(Optional<Boolean> createAnonymous) {
            this.createAnonymous = createAnonymous;
            return this;
        }

        /**
         * <p>When <code>true</code>, enables real-time validation of ACH account and routing numbers. This is an add-on feature, contact Payabli for more information.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage achValidation(Boolean achValidation) {
            this.achValidation = Optional.ofNullable(achValidation);
            return this;
        }

        /**
         * <p>When <code>true</code>, enables real-time validation of ACH account and routing numbers. This is an add-on feature, contact Payabli for more information.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "achValidation", nulls = Nulls.SKIP)
        public _FinalStage achValidation(Optional<Boolean> achValidation) {
            this.achValidation = achValidation;
            return this;
        }

        /**
         * <p><em>Optional but recommended</em> A unique ID that you can include to prevent duplicating objects or transactions in the case that a request is sent more than once. This key isn't generated in Payabli, you must generate it yourself. This key persists for 2 minutes. After 2 minutes, you can reuse the key if needed.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage idempotencyKey(String idempotencyKey) {
            this.idempotencyKey = Optional.ofNullable(idempotencyKey);
            return this;
        }

        /**
         * <p><em>Optional but recommended</em> A unique ID that you can include to prevent duplicating objects or transactions in the case that a request is sent more than once. This key isn't generated in Payabli, you must generate it yourself. This key persists for 2 minutes. After 2 minutes, you can reuse the key if needed.</p>
         */
        @java.lang.Override
        public _FinalStage idempotencyKey(Optional<String> idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        @java.lang.Override
        public AddMethodRequest build() {
            return new AddMethodRequest(
                    idempotencyKey,
                    achValidation,
                    createAnonymous,
                    forceCustomerCreation,
                    temporary,
                    body,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
