/**
 * This file was auto-generated by Fern from our API Definition.
 */
package io.github.payabli.resources.boarding.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.payabli.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetExternalApplicationRequest.Builder.class)
public final class GetExternalApplicationRequest {
    private final Optional<Boolean> sendEmail;

    private final Map<String, Object> additionalProperties;

    private GetExternalApplicationRequest(Optional<Boolean> sendEmail, Map<String, Object> additionalProperties) {
        this.sendEmail = sendEmail;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return If <code>true</code>, sends an email that includes the link to the application to the <code>mail2</code> address. Defaults to <code>false</code>.
     */
    @JsonProperty("sendEmail")
    public Optional<Boolean> getSendEmail() {
        return sendEmail;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetExternalApplicationRequest && equalTo((GetExternalApplicationRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetExternalApplicationRequest other) {
        return sendEmail.equals(other.sendEmail);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.sendEmail);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> sendEmail = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetExternalApplicationRequest other) {
            sendEmail(other.getSendEmail());
            return this;
        }

        /**
         * <p>If <code>true</code>, sends an email that includes the link to the application to the <code>mail2</code> address. Defaults to <code>false</code>.</p>
         */
        @JsonSetter(value = "sendEmail", nulls = Nulls.SKIP)
        public Builder sendEmail(Optional<Boolean> sendEmail) {
            this.sendEmail = sendEmail;
            return this;
        }

        public Builder sendEmail(Boolean sendEmail) {
            this.sendEmail = Optional.ofNullable(sendEmail);
            return this;
        }

        public GetExternalApplicationRequest build() {
            return new GetExternalApplicationRequest(sendEmail, additionalProperties);
        }
    }
}
